### ISSUE TITLE
bugged "challenge" computation for `getChallengeForGetWeb3Secret`

### ISSUE THREAD

**Issue by PierreJeanjacquot** [iExecBlockchainComputing/iexec-sms#106]
Unlike other `getChallengeForX` methods, the `DOMAIN` is not hashed before being used in `HashUtils.concatenateAndHash`

- `getChallengeForGetWeb3Secret`:
```java
    public String getChallengeForGetWeb3Secret(String secretAddress) {
        return HashUtils.concatenateAndHash(
                DOMAIN,
                secretAddress);
    }
```

- other `getChallengeForX`:

```java
    public String getChallengeForGetWeb2Secret(String ownerAddress,
                                               String secretKey) {
        return HashUtils.concatenateAndHash(
                Hash.sha3String(DOMAIN),
                ownerAddress,
                Hash.sha3String(secretKey));
    }
```

Going a bit further: 

`HashUtils.concatenateAndHash(String... hexaString)` expects params to be `hexaString` and finally use them in web3j `Numeric.hexStringToByteArray(hexaString)`.

Here `DOMAIN` value is not hex encoded and may lead to unexpected results.

**Comment by PierreJeanjacquot** [comment]
I'm currently working around the bug using the output of `Numeric.hexStringToByteArray('IEXEC_SMS_DOMAIN')` => `0xfefebfefefcffaef`

**Comment by jeremyjams** [comment]
At the current time, it is not possible to retrieve web3 secret anymore (see https://github.com/iExecBlockchainComputing/iexec-sms/blob/230cd86274909226861083ca351d4b5725b1da90/src/main/java/com/iexec/sms/secret/SecretController.java#L53), closing issue.
